CREATE TABLE exchange_rates (
    id              BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    from_currency   VARCHAR(3)      NOT NULL,
    to_currency     VARCHAR(3)      NOT NULL,
    rate            DECIMAL(18, 8)  NOT NULL,
    last_updated    TIMESTAMP       NOT NULL DEFAULT NOW(),
    source          VARCHAR(10)     NOT NULL DEFAULT 'API',
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_exchange_rates PRIMARY KEY (id),
    CONSTRAINT uq_exchange_rates_pair UNIQUE (from_currency, to_currency),
    CONSTRAINT chk_exchange_rates_source CHECK (source IN ('API', 'MANUAL')),
    CONSTRAINT chk_exchange_rates_positive CHECK (rate > 0)
);

CREATE INDEX idx_exchange_rates_pair ON exchange_rates (from_currency, to_currency);
CREATE INDEX idx_exchange_rates_active ON exchange_rates (is_active);
CREATE INDEX idx_exchange_rates_last_updated ON exchange_rates (last_updated);
