CREATE TABLE logs (
    log_id      BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event       VARCHAR(100)    NOT NULL,
    event_type  VARCHAR(50)     NOT NULL,
    timestamp   TIMESTAMP       NOT NULL DEFAULT NOW(),
    user_id     UUID,
    ip_address  VARCHAR(45),
    details     JSON,

    CONSTRAINT pk_logs PRIMARY KEY (log_id),
    CONSTRAINT fk_logs_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE SET NULL
);

CREATE INDEX idx_logs_timestamp ON logs (timestamp DESC);
CREATE INDEX idx_logs_user_id ON logs (user_id);
CREATE INDEX idx_logs_event_type ON logs (event_type);
